apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx-rs
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: nginx-rs 
  template:
    metadata:
      labels:
        app: nginx-rs
    spec:
      containers:
      - name: nginx-server
        image: nginx
