apiVersion: v1
kind: PersistentVolume
metadata:
  name: logger-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteMany #type of access
  hostPath:
    path: "/logs" #host location