#Maintainer: Arbaaz
apiVersion: v1
kind: Service
metadata:
  name: service-headless
spec:
  clusterIP: None
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
